import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>André</h1>

        <Link
          href={{
            pathname: "/page01",
            query: {
              question: "Why?",
              answers: ["because 01", "because 02"],
            },
          }}
        >
          Example page
        </Link>
      </main>

      <footer></footer>
    </div>
  );
}
